services:
  nginx:
    build: requirements/nginx/.
    ports:
      -  443:443
    networks:
      - inception-net
      - internal-net
    volumes:
      - wordpress-vol:/home/tools
    restart: unless-stopped
    env_file:
      - .env
  mariadb:
    build: requirements/mariadb/.
    env_file:
      - .env
    ports:
      - "3308:3306"
volumes:
  DB:
  wordpress-vol:
networks:
  inception-net:
  internal-net:
    internal: true