services:

  nginx:
    container_name: nginx
    image: nginx:nginx
    build: requirements/nginx/.
    ports:
        - "443:443"
    networks:
      - internal-net
    volumes:
      - wordpress-vol:/var/www/html/
    # restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - wordpress
  

  mariadb:
    container_name: mariadb
    image: mariadb:mariadb
    build: requirements/mariadb/.
    env_file:
      - .env
    networks:
      - internal-net
    # restart: unless-stopped
    volumes:
      - DB:/var/lib/mysql


  wordpress:
    container_name: wordpress
    image: wordpress:wordpress
    build: requirements/wordpress/.
    env_file:
      - .env
    networks:
      - internal-net
    # restart: unless-stopped
    volumes:
      - wordpress-vol:/var/www/html/
    depends_on:
      - mariadb
volumes:
  DB:
  wordpress-vol:
networks:
  internal-net:
    driver: bridge


    