version: '2.18.1'
services:
  nginx:
    build: requirements/nginx/.
    ports:
      -  443:443
    networks:
      - web-net
      - internal-net
    volumes:
      # - type: volume
      # - source: wordpress-vol
      # - target: /code
      - wordpress-vol:/home/tools
  mariadb:
    build: requirements/mariadb/.
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
  # wordpress:
volumes:
  DB:
  wordpress-vol:
networks:
  inception-net:
  internal-net:
    internal: true