services:

  nginx:
    container_name: nginx
    image: nginx:inception
    build: requirements/nginx/.
    ports:
        - "443:443"
    networks:
      - internal-net
    volumes:
      - wordpress:/var/www/html/
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - wordpress
  

  mariadb:
    container_name: mariadb
    image: mariadb:inception
    build: requirements/mariadb/.
    env_file:
      - .env
    networks:
      - internal-net
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql


  wordpress:
    container_name: wordpress
    image: wordpress:inception
    build: requirements/wordpress/.
    env_file:
      - .env
    networks:
      - internal-net
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html/
    depends_on:
      - mariadb

networks:
  internal-net:
    name: internal-net
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device:  /Users/ebelfkih/data/wordpress  ## Change this to your path
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /Users/ebelfkih/data/mariadb/  ## Change this to your path
      o: bind
      type: none